### ISSUE TITLE
Master zu Slave Verbindungsaufbau und RPC

### ISSUE THREAD

**Issue by jmpunkt** [bp-flugsimulator/server#11]
### Intro
Wie sieht das aus mit dem Hochfahren der Slaves. Geplant war dass der Master von allen gespeicherten Slaves die MAC Adresse nimmt und ein Befehl Wake-On-Lan (WOL) an diese sendet. Da das RPC Protokoll so aufgebaut ist das ein Client immer die Funktionen auf einem Server aufruft würde das für unseren Aufbau bedeuten dass auf jedem Slave ein RPC Server läuft auf den sich der Master verbinden kann und dort befehel aufführen kann. 

##### Ein Verbindungsaufbau würde dann wie folgt ablaufen.
WOL -> (Slave startet) -> Slave sendet HTTP request an Master (teilt ihm mit dass er gestartet ist) -> Master verbindet sich auf den Slave (RPC Server) -> Fertig

### Problem 
Die die Verbindunge jedes mal neu gestartet werden müssen brauchen wir eine Struktur die, die Verbindungen hält. Auch müsste man gleichzeitig auf diese Strukture zugreifen (Django). 

### Lösung
* FIFO, die Elemente wären dann sowas wie (ID, COMMAND_IDENTIFIER, COMMAND_ARGS), wobei ID der id aus der Datenbank entspricht. COMMAND_IDENTIFIER und COMMAND_ARGS übergibt man einfach an RPC. Die FIFO kann man in einem seperaten Thread abarbeiten. Gibt es solche FIFO's in Python?
* Django Tasks? Ist es da möglich die Verbindungen zu speichern? Bzw. kann jemand eine Skizze zu dem Verfahren angeben?
* Andere Möglichkeiten?

**Comment by Miterion** [comment]
Ich finde die Task Queue nicht schlecht. Es gibt da auch entsprechende Bibliotheken (z.B. [django Q](https://github.com/Koed00/django-q)). Dann könnte der größte Teil darauf abgewälzt werden.

**Comment by jmpunkt** [comment]
## Into
Hab in den letzten Tagen nach einen passenden Framework gesucht. Nachdem ich mich mit Twisted auseinandergesetzt habe bin ich auf zu dem Entschluss gekommen, dass das in unsere Environment nicht ohne Hacks funktionieren wird. Somit habe ich nach einen RPC Framework gesucht welches asyncio verwenden, da DjangoQ damit auch umgehen kann (höchstwahrscheinlich). Das Framework heißt aiohttp-xmlrpc. 

## Code
#### client.py
```py
import asyncio
from aiohttp_xmlrpc.client import ServerProxy


async def routine():
    client = ServerProxy("http://127.0.0.1:8080/")
    print(await client.add(1, 2))
    client.close()

if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(
        asyncio.gather(
            routine(),
            routine(),
            routine(),
            routine(),
            routine(),
            routine(),
            routine(),
            routine(),
            routine(),
            routine(),
            routine(),
            routine(),
            routine(),
            routine(),
            routine(),
            routine(),
            routine(),
            routine(),
            routine(),
            routine(),
        ))
``` 
#### server.py
```py
import asyncio
from aiohttp import web
from aiohttp_xmlrpc import handler
from random import randrange


class Math(handler.XMLRPCView):
    async def rpc_add(self, a, b):
        sle = randrange(10)
        await asyncio.sleep(sle)
        return sle


app = web.Application()
app.router.add_route('*', '/', Math)

if __name__ == "__main__":
    web.run_app(app)```

Wenn man das Beispiel ausführt bekommt man in der Konsole eine geordnete Liste (aufsteigend) wie lange der Call geschlafen hat. Wenn man das mit dem standard XML-RPC ausführt bekommt man keine geordnete Liste. 

## Warum async?
Da wir vor habe auf den Slaves Programme laufen zu lassen ist es ratsam diese mit asyncio im Hintergrund zu halten und sofort ein Feedback zu bekommen, falls dieser Prozess sich beendet. Da es meiner Meinung nach nicht sinnvoll ist in einem bestimmten Zeitintervall den Status dieses Programmes abzufragen sollten wir die zuvor genannte Methode benutzten. Nun ist es noch nicht geklärt was mit dem Output passiert. Auf der einen Seite kann man diesen zum Master streamen oder in Dateien auf dem Slave halten und bei Bedarf abfragen. Die Frage ist also "Wird der Output auf dem Master in Echtzeit 

## Testen
Ich hab momentan keine Idee wie ich den Code so schreibe dass er auf unsere Test Environment läuft. Denn falls das auf allen Zielsystemen ohne Fehler läuft wäre das hier das best mögliche Szenario.

**Comment by GreenM0nst3r** [comment]
## Zum Testen
Ich würde vorschlagen das testen des Slaves auf zwei Wegen zu machen:
1. Unittesting aller per RPC angebotenen Klassen ohne RPC
2. Integrationtesting aller angebotenen Funktionen, die den Slave als Subprozess starten, über RPC die Ausführung starten und danach auf die Veränderungen des ganzen Systems achten.

**Comment by jmpunkt** [comment]
![](https://github.com/bp-flugsimulator/qs/raw/master/vortraege/1_vortragstraining/img/architecture.png)

So sollte am Ende unser System aussehen.
