### ISSUE TITLE
Speichern von Daten

### ISSUE THREAD

**Issue by jmpunkt** [bp-flugsimulator/server#4]
### Intro
Wir hatten und auf Konfigurations Dateien festgelegt, um Daten zu speichern. Aber da die Integration von SQL in Django sehr einfach ist sollten wir vielleicht in erwägung ziehen für alle Konfigurationen SQL zu benutzten. Vorzugweise Sqlite, da es sehr klein ist und auch sehr portabel sein sollte.

### Vorteile
* Man muss keine ConfigFile Klasse implentieren, die auch mit Django funktioniert. (großer Aufwand?)
* Migrationen/etc. sind einfach
* Einfacher Umgang mit Queries
* Keine Probleme im Mehrnutzerbetrieb
* Daten sind gesichert. (Stromausfall)
* Weniger Fehleranfällig

### Nachteile
* Overhead?
* Sqlite Portable genug?

### Fragen
* Da das ausschließlich auf dem Master läuft, sollte man sich überlegen ob das auch auf WindowsXP laufen muss.
* Wie komplex sind die Konfigurationsdateien?

**Comment by GreenM0nst3r** [comment]
Eine ähnliche Idee hatten wir auch während der implimentierung von #3.

**Comment by Miterion** [comment]
Zu den Nachteilen:
* Overhead
  * Relativ wenig da direkt in Django eingebaut und daher recht nutzerfreundlich
* Sqlite Portable genug?
 * Es funktioniert unter Linux und Mac OS ohne Probleme (habe ich getestet). Windows wird auch von sqlite unterstützt, sollte daher eigentlich auch laufen

**Comment by jmpunkt** [comment]
Muss man Sqlite manuell installieren? Oder kommt das mit pip mit?

**Comment by Miterion** [comment]
@jmpunkt Das kommt automatisch mit, ist eine Abhängigkeit (bzw direkt im django paket drin)
