### ISSUE TITLE
HTTP Routen

### ISSUE THREAD

**Issue by jmpunkt** [bp-flugsimulator/server#5]
Wie wollen wir die Routen gestalten? Mir fallen zwei Möglichkeiten ein.

### REST-like
Diese Routen geben kein HTML sondern Json, XML, etc. zurück und werden via async Requests aufgerufen.
Dann ist z.B. die Route /slaves für das Anzeigen des Status von dem Client zuständig und z.B. /api/slaves mit POST zum Hinzufügen von Slaves.

### Redirect
Oder man hat /slaves zum Anzeigen mit GET und wenn man ein POST Befehl an /slaves schickt wird dieser ausgeführt und im Anschluss wieder an /slaves redirected. Fehler Codes oder andere Sachen werden dann per Cookie oder URL mitgegeben.

### Pro REST-like
* Einfach auf dem Server zu implementieren
* Flexibler

### Contra REST-like
* Man benötigt warscheinlich mehr Javascript -> Wir schwer in der Zukunft was auf anhieb zu ändern?
* Ohne jQuery oder ähnliches aufwendig
* Funktioniert warscheinlich nicht so gut mit Django??

**Comment by GreenM0nst3r** [comment]
Meiner Meinung nach würde ich eher einen Rest-like verwenden oder sogar die Verwendung von Websockets vorschlagen, da wir viele dynamische Anzeigen (Status von Slaves/status von Programmen) haben, die man darüber besser Lösen könnte als durch redirects.
