### ISSUE TITLE
Wiederherstellung der BACKUP's

### ISSUE THREAD

**Issue by leo-lxps** [bp-flugsimulator/server#77]
## Eingabeparameter
- Pfad zum Source? 
- Pfad zur Destination? 
> Es muss beides übergeben werden da ein Pfad aus beidem bestehen kann
```
z.B.:
./src/... -> ./dest/... => ./dest/src/...
```
- BACKUP-Endung?
### Oder
- Pfad zum direkten BACKUP?
> Es kann der original Pfad erstellt werden und es ist keine BACKUP-Endung nötig
Es ist allerdings mehr Aufwand diesen Eingabeparameter zu generieren.

## Ordner BACKUP's
Es kann nicht garantiert werden, dass der Ordner von unserem Programm erstellt wurde!
> Bei Links ist das egal aber bei Ordnern nicht.
**Zudem muss der gesamte Ordner gelöscht werden!**
Vorschlag von @jmpunkt war Hashes zu benutzen.

**Comment by Miterion** [comment]
Können wir den Backup Ordner nicht in unserem eigenen Verzeichnis anlegen?

**Comment by leo-lxps** [comment]
Dann müsste man die Files vom Ordner in unseren kopieren, das könnte unter Umständen dauern.
Bis jetzt benennen wir ja nur den Ordner um und erstellen Ordner mit Links.

**Comment by Miterion** [comment]
Wir könnten sie verschieben, das geht sehr schnell

**Comment by leo-lxps** [comment]
Ich wollte halt nicht deren Daten anfassen. Und wenn das Backup-restoren mal nicht gemacht wird, ist es schwer das sie ihre Files wiederfinden, so stehen sie direkt im selben Ordner als Backup gekennzeichnet.

**Comment by jmpunkt** [comment]
## Ablauf

1. Jede Datei bekommt ein Hash
2. Zeigt eine Datei auf den gleichen Pfad muss der Benutzer entscheiden welche er aktivieren will, falls er keine auswählt wird die Default Datei verwendet.
3. Die Default Datei ist die, die beim erstellen der Datei (im Webinterface) vorhanden oder nicht vorhanden ist. 
4. Die Default Datei wird nach dem Stop des Programmes wieder hergestellt.
5. Ändert ein Benutzer eine Datei im Betrieb wird die Änderung überschrieben
6. Ändert ein Benutzer die Datei außerhalb des Betriebs wird diese die neue Default Datei, dabei wird der Hash Wert in unserer Datenbank 

### Zusatz Nr. 1
Ein weitere Zustatz wäre, dass man die Änderung seperat Speichert. Dann wäre die Änderung, die außerhalb des Betriebs zustande kommt, nicht die neue Default Datei sond wieder eine neue Datei. Z.B. würde sie dann einen Suffix haben, der aus dem momentanen Datum besteht.

### Zusatz Nr. 2
Ein weitere Zustatz wäre, dass man Änderung von den Dateien im Betrieb erlaubt und diese dann übernimmt. Halte ich aber nicht für, da es sonst einfach wäre das System zu zerschießen (aus der Sicht des Users).
